### PR TITLE
Initial Home Page

### PR DESCRIPTION
**Pull request by gezgblack**
In this PR I have just created out initial simple home page and also added some of the bootstrap.

### CODE REVIEW

**Comment by Sukrat** [comment]
:+1: I guess we should use NodeJs if we doing with angularJs?

**Comment by gezgblack** [comment]
I would say so, you got experience using NodeJs?

**Comment by Sukrat** [comment]
Yup i know NodeJs. So i ll just setup the environment for the same. Also we ll not be using nodejs for devolpment only for certain task. If we ever make API then we ll use dotnet as we both are good at it.

**Comment by gezgblack** [comment]
Sounds good dude :+1: I have very little experience with NodeJs, but am a fast learner :)

**Pull request merged**
